# Generated by Django 3.0.5 on 2020-04-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='./images')),
                ('title', models.CharField(max_length=100)),
                ('pub_data', models.DateTimeField(verbose_name='publishing date')),
                ('user_name', models.CharField(default='', max_length=25)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=25)),
                ('text', models.CharField(max_length=500)),
                ('pub_data', models.DateTimeField(verbose_name='publishing date')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias.UserPost')),
            ],
        ),
    ]
