# Generated by Django 3.0.5 on 2020-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0002_auto_20200428_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
