# Generated by Django 3.0.5 on 2020-04-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0002_userpost_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=25)),
                ('text', models.CharField(max_length=500)),
                ('pub_data', models.DateTimeField(verbose_name='publishing date')),
            ],
        ),
        migrations.AddField(
            model_name='userpost',
            name='comment_ids',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
