# Generated by Django 3.0.5 on 2020-04-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0003_auto_20200422_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='comment_ids',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='user_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='experiencias.UserPost'),
            preserve_default=False,
        ),
    ]
