# Generated by Django 3.0.5 on 2020-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0005_auto_20200425_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
