# Generated by Django 3.0.5 on 2020-05-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0006_auto_20200425_1732'),
        ('experiencias', '0003_auto_20200428_1225'),
    ]

    operations = [
    ]
