# Generated by Django 3.0.5 on 2020-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0007_merge_20200502_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
